### PR TITLE
Config block chaining fix

### PR DESCRIPTION
**Pull request by lahmann**
This should fix the reported issue #122.

### CODE REVIEW

**Comment by acelaya** [comment]
Can you provide a test case covering this situation?

**Comment by lahmann** [comment]
A `mail.global.php` config with the following contents should show this issue (and that it's solved by adding the do-while-loop):

```
return [
    'acmailer_options' => [
        'default' => [
            //unaltered default values from mail.global.php.dist
        ],
        'foo' => [
            'extends' => 'default',
            'message_options' => [
                'from' => 'me@here.com'
            ]
        ],
        'bar' => [
            'extends' => 'foo',
            'message_options' => [
                'to' => 'me@here.com',
                'subject' => 'Foobar subject'
            ]
        ]
    ],
];
```

**Comment by acelaya** [comment]
I mean if you can create a unit test that tests this case :-)

**Comment by lahmann** [comment]
I was afraid you actually meant a unit test... ;)
Not today, maybe tomorrow.

**Comment by acelaya** [comment]
Perfect, thanks.

--
Alejandro Celaya Alastrué

**Comment by lahmann** [comment]
There you go. :)

**Comment by acelaya** [comment]
Looks good, thanks

**Pull request merged**
