### PR TITLE
Added replyTo argument

### PR DESCRIPTION
**Pull request by bartoszzajac**

### CODE REVIEW

**Comment by acelaya** [comment]
Looks good, but could you update the `SendMailPluginTest` covering the new case?

**Comment by acelaya** [comment]
By the way, you have duplicated the code used in the `from` param. Could you define a protected method wrapping the duplicated logic?

**Comment by bartoszzajac** [comment]
I will try :)

**Comment by bartoszzajac** [comment]
Testing hang?

**Comment by acelaya** [comment]
Yes, I meant to create a function that wrapps processing both the from and replyTo params, since the logic is the same.

**Comment by bartoszzajac** [comment]
I did this.

**Comment by acelaya** [comment]
Try this approach. It is less verbose and better fulfills object calisthenics.

```php
protected function applyArrayArgs(array $args, $key)
{
    if (! isset($args[$key])) {
        return;
    }

    $arg = $args[$key];
    $setter = 'set' . ucfirst($key);

    if (is_array($arg)) {
        $this->mailService->getMessage()->{$setter}(array_keys($arg)[0], array_values($arg)[0]);
        return;
    }

    $this->mailService->getMessage()->{$setter}($arg);
}
```

**Comment by acelaya** [comment]
Then, if you add the tests from the other branch and build passes, I'll probably merge your pull request :)

**Comment by acelaya** [comment]
Looks great. Thanks for the effort.
I'll try to cherry-pick it into v5.x too

**Comment by bartoszzajac** [comment]
But test coverage is still 98%. Shouldn't applyArrayArgs function have their own test?

**Comment by acelaya** [comment]
The code coverage was 98% already. The `SendMailPlugin` is now 100% covered, since that protected method is already tested.

**Comment by bartoszzajac** [comment]
I don't like my function also. Too much 'if'. You showed me some new things
that I never saw in php. I will correct in monday because now I'm only on
phone.

22 paź 2016 6:19 PM "Alejandro Celaya" <notifications@github.com>
napisał(a):

**Pull request merged**
