### PR TITLE
Feature/dist config enhancements

### PR DESCRIPTION
**Pull request by jeremiahsmall**
When I committed again on the branch for #106 it seems to have become detached from that PR. Anyway, here's a modification that only adds a note about best practice of not committing credentials, (and also the docblock housekeeping).

### CODE REVIEW

**Comment by jeremiahsmall** [comment]
Gah! I accidentally PR'd to master instead of develop, but I see they're in sync anyway, so probably doesn't matter.

**Comment by acelaya** [comment]
I can live with this. I think it is not a bad idea to mention the credentials thing. If build passes I'l merge it.
And don't worry, most of the pull requests are made to master ;-)

**Comment by jeremiahsmall** [comment]
Cool. BTW, 5.x is a great update. Much nicer configs. Thanks for creating this module.

**Comment by acelaya** [comment]
Thank you for contributing

**Pull request merged**
